### ISSUE TITLE
Pseudo parameters no longer work in custom variables or resources

### ISSUE THREAD

**Issue by adsurg** [svdgraaf/serverless-pseudo-parameters#10]
The earlier evaluation means that "#{AWS::StackName}-lock" is no longer being substituted.  This is working in v1.3.2.

```
resources:
  Resources:
    lambdaLockDb:
      Type: 'AWS::DynamoDB::Table'
      ...
      TableName: "#{AWS::StackName}-lock"
```

```
provider:
  name: aws
  ...
  environment:
    LOCK_TABLE: ${self:custom.lockTableName}
custom:
  lockTableName: "#{AWS::StackName}-lock"
```
