### ISSUE TITLE
Doesn't work with serverless-plugin-split-stacks

### ISSUE THREAD

**Issue by craig-dae** [svdgraaf/serverless-pseudo-parameters#28]
With serverless-plugin-split-stacks: 1.7.0 and serverless: 1.38.0,

```
1 validation error detected: Value 'arn:#{AWS::Partition}:lambda:us-east-1:123456789012:function:fake-name-authorizer' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))? (Service: AWSLambda; Status Code: 400; Error Code: ValidationException; Request ID: 8bdef293-3d51-11e9-a53f-535a5b27c45f)
```

**Comment by craig-dae** [comment]
Sorry, it has been too long for me to say confidently. I believe it was a result of serverless-plugin-split stacks + serverless-pseudo-parameters + serverless-iam-roles-per-function

We were using ARNs in the function IAM roles. The arns used the Partition pseudo params. 

```
#projects
  query_projects:
    handler: accounts/projects/query_projects.lambda_handler
    layers: ${self:custom.layers}
    events:   
      - schedule: rate(5 minutes)
      - http: 
          path: accounts/{accountId}/projects/
          method: get
          authorizer: arn:#{AWS::Partition}:lambda:${self:provider.environment.Region}:${self:provider.environment.AccountId}:function:auth-${self:custom.stage}-authorizer
          cors: ${file(./cors.yml)}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
          - "dynamodb:Query"
        Resource: 
          - "arn:#{AWS::Partition}:dynamodb:${self:provider.environment.Region}:${self:provider.environment.AccountId}:table/${self:provider.environment.ProjectDynamoDBTable}"
          - "arn:#{AWS::Partition}:dynamodb:${self:provider.environment.Region}:${self:provider.environment.AccountId}:table/${self:provider.environment.ProjectDynamoDBTable}/*/*"      
```
