### ISSUE TITLE
Using pseudoparameters with custom stage variable with http event

### ISSUE THREAD

**Issue by vdanniel** [svdgraaf/serverless-pseudo-parameters#29]
custom:
    envPref: '#{environmentPrefix}'
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.envPref}
functions:
  processEvent:
    handler: handler.processEventFunction
    name: 'dan-#{environmentPrefix}-process-event'
    events:
      - http:
          path: tdi/processevent
          method: post
          cors: true
          private: true

With the above setup, it fails to create the http scaffolding. 

any advise.

**Comment by vdanniel** [comment]
@cipri-p

**Comment by svdgraaf** [comment]
You are using`#{environmentPrefix}`, but I don't see it being set anywhere. I take it is an environment variable, if so, this should work:

```
custom:
  envPref: '#{env:environmentPrefix}'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.envPref}

functions:
  processEvent:
    handler: handler.processEventFunction
    name: 'dan-${self:custom.envPref}-process-event'
    events:
      - http:
        path: tdi/processevent
        method: post
        cors: true
        private: true
```
