### ISSUE TITLE
Pseudo-parameters not substituted in Lambda SNS Subscriptions

### ISSUE THREAD

**Issue by janikarh** [svdgraaf/serverless-pseudo-parameters#42]
I tried to set a SNS Subscription for a Lambda function, with existing SNS Topic with ARN. If I set the ARN "manually" everything works as it should.

I configured the parameters as follows:
```yaml
custom:
  requestTopicName: 'requests'

functions:
  handleInstallRequests:
      description: This function subscribes to SNS and handles the installation requests.
      runtime: python3.7
      memorySize: 128
      timeout: 30
      handler: install_req_handler.lambda_handler
      events:
        - sns:
            arn: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.requestTopicName}"
            filterPolicy:
              action: ["installation_request"]
```

When packaging, the pseudo-parameters do not get replaced, and the CloudFormation template ends up containing:

```json
...
"TopicArn": {
          "Fn::Sub": "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:requests"
        },
...
````

I am using `serverless-python-requirements` for packaging.

Am I doing something wrong, or is this a bug?
