### ISSUE TITLE
Environment variable not added properly to all lambdas 

### ISSUE THREAD

**Issue by MarcMagdi** [svdgraaf/serverless-pseudo-parameters#55]
Hi, 
I am trying to set the AWS ACCOUNT_ID and Region as an environment variable but with no luck. 
I have added it under provider as follows: 

```yaml
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: '#{AWS::Region}'
    AWS_ACOUNT_ID: '#{AWS::AccountId}'
```

After this, the env variable was added to some of the lambdas correctly and in the other ones was just a plain text as follows:
![image](https://user-images.githubusercontent.com/16214697/79204158-653f3480-7e3c-11ea-9689-33ba209b2c1a.png)
![image](https://user-images.githubusercontent.com/16214697/79204168-6a03e880-7e3c-11ea-995d-e5bba2f67744.png)

I tried this on function level and global level and the same issue occurs. 
The only difference I found between the functions that were getting the right values is that they are connected to an API Gateway, but all lambdas that aren't don't get the right value.
