### ISSUE TITLE
#{AWS::AccountId} isn't being substituted when part of cfnRole variable

### ISSUE THREAD

**Issue by FergusMcGlynn** [svdgraaf/serverless-pseudo-parameters#75]
I'm trying to use `#{AWS::AccountId}` as part of the `cfnRole` variable in my `serverless.yml` file, but it's not being substituted. Here is the relevant section of `serverless.yml`:

```
plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  cfnRole: "arn:aws:iam::#{AWS:AccountId}:role/MyRole"
```

When I run `serverless deploy`, I get the error message `Cross-account pass role is not allowed`, and when I turn on debugging with `SLS_DEBUG=true`, I can see that the role it's using to do the deployment is

```
arn:aws:iam::#{AWS:AccountId}:role/MyRole
```

i.e. the pseudo parameter is not being substituted. If I replace `#{AWS:AccountId}` with the literal value (i.e. `cfnRole: "arn:aws:iam::12345678901234:role/MyRole"`) then the deployment works fine.  Does anyone know why parameter substitution isn't happening here?
