### ISSUE TITLE
Cannot Use Pseudo Parameters In S3 Bucket for events

### ISSUE THREAD

**Issue by andrewtomai** [svdgraaf/serverless-pseudo-parameters#76]
### Issue:
I want to create a service that uses an S3 bucket as an event source, and I want the `#{AWS::AccountId}` to be in the bucket name to guarantee a unique bucket name.  However, this does not work as expected;  when trying to deploy the service, I receive an error message:

`Bucket name should not contain uppercase characters.`

#### Environment Information:
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.14.1
     Framework Version:         1.80.0
     Plugin Version:            3.8.1
     SDK Version:               2.3.1
     Components Version:        2.34.9
```

#### serverless.yml
```yml
service: sample-bucket-project
provider:
  name: aws
  region: us-west-2
  runtime: nodejs12.x
plugins:
  - serverless-pseudo-parameters

functions:
  test:
    handler: index.handler
    events:
      - s3:
          bucket: my-events-bucket-#{AWS::AccountId}
```

#### Full command output:
```
$ serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  my-events-bucket-#{AWS::AccountId} - Bucket name should not contain uppercase characters. Please check provider.s3.my-events-bucket-#{AWS::AccountId} and/or s3 events of function "test".

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.14.1
     Framework Version:         1.80.0
     Plugin Version:            3.8.1
     SDK Version:               2.3.1
     Components Version:        2.34.9
```
