### ISSUE TITLE
Pseudo-parameters not substituted for deploymentBucket

### ISSUE THREAD

**Issue by nikita-sheremet-clearscale** [svdgraaf/serverless-pseudo-parameters#77]
Look at serverless
```
service: database

frameworkVersion: ">=1.38.0 <2.0.0"

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-cf-vars
  - serverless-parameters
  - serverless-s3-deploy
  - serverless-scriptable-plugin

provider:
  name: aws
  stage: dev
  region: us-east=1
  deploymentBucket:
    name: my_bucket-#{AWS::AccountId}-#{AWS::Region}-name
    blockPublicAccess: true

resources:
  Resources:
    Database:
      Type: AWS::Glue::Database
      Properties:
        CatalogId: "#{AWS::AccountId}"
        DatabaseInput:
          Name: some_name
```

It fails with error:

```
cmd.exe /c "serverless deploy"
 
  Serverless Error ---------------------------------------
 
  Bucket name cannot contain uppercase letters. my_bucket-#{AWS::AccountId}-#{AWS::Region}-name
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.15.0
     Framework Version:         1.53.0
     Plugin Version:            3.1.1
     SDK Version:               2.1.1
     Components Core Version:   1.1.1
     Components CLI Version:    1.2.3
 

Process finished with exit code 1
```
